#!/bin/bash

target="$HOME/apps/joinbox/codedeploy/master/src/autoDeploy.sh"

if [ ! -f "$target" ]; then
    echo "The deployr repository is missing! Cannot call $target"
    exit 1
fi

source "$HOME/apps/joinbox/codedeploy/master/src/autoDeploy.sh" $1 $2