#!/bin/bash

target="$HOME/apps/joinbox/codedeploy/master/src/validate.sh"

if [ ! -f "$target" ]; then
    echo "The deployr repository is missing! Cannot call $target"
    exit 1
fi

if [ ! -f "/etc/deployr/deployr.conf" ]; then
    echo "missing the config file /etc/deployr/deployr.conf!"
    exit 1
fi



# get environment
installEnv=$(awk '/^env/{print $3}' /etc/deployr/deployr.conf)


source "$HOME/apps/joinbox/codedeploy/master/src/validate.sh" $1 $2 $installEnv